DROP SCHEMA IF EXISTS s_m;
CREATE SCHEMA s_m;
USE s_m;

CREATE TABLE IF NOT EXISTS `user` (
	id INT(11) AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(50) NOT NULL UNIQUE,
	`password` CHAR(80) NOT NULL,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	mobile VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL UNIQUE,
	active INT(1) DEFAULT 1,
	created_at DATETIME NOT NULL,
	modified_at DATETIME NOT NULL
)

CREATE TABLE IF NOT EXISTS `role` (
	id INT(11) AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(50) NOT NULL UNIQUE
)

CREATE TABLE IF NOT EXISTS `users_roles` (
	user_id INT(11) NOT NULL,
	role_id INT(11) NOT NULL,
	
	PRIMARY KEY (`user_id`,`role_id`),
	
	KEY `FK_ROLE_idx` (`role_id`),
	
	CONSTRAINT `FK_USER` FOREIGN KEY (`user_id`)
	REFERENCES `user` (`id`)
	ON DELETE NO ACTION ON UPDATE NO ACTION,
	
	CONSTRAINT `FK_ROLE` FOREIGN KEY (`role_id`) 
	REFERENCES `role` (`id`) 
	ON DELETE NO ACTION ON UPDATE NO ACTION
)

CREATE TABLE IF NOT EXISTS user_address (

);

CREATE TABLE IF NOT EXISTS user_payment (

);

CREATE TABLE IF NOT EXISTS user_history (

);

CREATE TABLE IF NOT EXISTS product_category (

);

CREATE TABLE IF NOT EXISTS product (

);

CREATE TABLE IF NOT EXISTS product_inventory (

);

CREATE TABLE IF NOT EXISTS coupon (

);

CREATE TABLE IF NOT EXISTS discount (

);

CREATE TABLE IF NOT EXISTS cart_item (

);

CREATE TABLE IF NOT EXISTS shopping_session (

);

CREATE TABLE IF NOT EXISTS order_details (

);

CREATE TABLE IF NOT EXISTS order_items (

);

CREATE TABLE IF NOT EXISTS payment_details (

);

CREATE TABLE IF NOT EXISTS wishlist (

);
